sudo: true
language: python
dist: xenial
python:
- '3.7'
before_install:
- openssl aes-256-cbc -K $encrypted_d55f894abbe8_key -iv $encrypted_d55f894abbe8_iv -in client-secret.json.enc -out client-secret.json -d
- export PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/lib"
install:
- pip install -r requirements-prd.txt -t lib/
- pip install requests --upgrade -t lib/
- sudo apt-get install -qq libexempi3
- cd ubyssey/static_src
- npm install -g gulp
- npm install
- npm ddp
script:
- gulp build
after_success:
- rm -rf node_modules
- cd ${TRAVIS_BUILD_DIR}
# use deploy settings
- export DJANGO_SETTINGS_MODULE="config.settings.production"
- travis_wait python manage.py collectstatic --noinput
- rm -rf .git/ ubyssey/static_src/
- pip install -I google-cloud-storage==1.13.2 -t lib/
- ls lib/
- ls lib/django/


deploy:
  - provider: gae
    keyfile: client-secret.json
    project: ubyssey-prd
    default: true
    version: ubyssey-${TRAVIS_TAG//./-} # Replace periods with hyphens
    skip_cleanup: true
    on:
      tags: true
